### PR TITLE
add SmallRye Fault Tolerance documentation to the site

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Draft for now, because the 5.0.0 release isn't out yet (Sonatype woes).

**Comment by Ladicek** [comment]
5.0.0 is released, this is ready to merge.

**Review by radcortez — DISMISSED** [review]

**Comment by Ladicek** [comment]
Sorry, had to rebase :-)

**Comment by Ladicek** [comment]
Ah I found I can force-merge as I'm an admin :laughing: Gonna do that, the content of the PR didn't change, it was just a rebase.

**Pull request merged**
