### PR TITLE
Fix the heavy background image and also fix #11

### LINKED ISSUE #11: Styling of the homepage
I like the background image but the text is not very readable... I think we should add some background-color to the hero div, something like:

Snímek obrazovky_2019-09-04_16-02-16

And apply similar styles to the top right menu and highlights too.

### PR DESCRIPTION
**Pull request by phillip-kruger**
Use media queries to load a more appropriate background image.
Also added fix for #11 

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by radcortez** [comment]
It seems that we have an issue with Semaphore. Is this because of the dependency updates?

**Comment by phillip-kruger** [comment]
Yea. I took it from https://github.com/smallrye/smallrye.github.io/pull/36/files. Let me revert that and we can do that in another PR if needed. Except if this is a quick fix in semaphore... ?

**Comment by radcortez** [comment]
The issue in Semaphore: 

jekyll-4.0.1 requires rubygems version >= 2.7.0, which is incompatible with the
current version, 2.6.14

**Comment by radcortez** [comment]
They only seem to support Ruby 2.6.3.

**Comment by radcortez** [comment]
This is also the last project that requires migration to GH Actions. I'll see if I can find some time to do it.

**Comment by phillip-kruger** [comment]
Ok, let me revert that for now, then we can merge here, and once GH Actions is in, we merge the upgrade PR.

**Comment by phillip-kruger** [comment]
@radcortez - please check now, I have reverted the version upgrades.

**Review by radcortez — APPROVED** [review]

**Pull request merged**
