### PR TITLE
Added SmallRye Config documentation.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by jmartisk** [comment]
Hmm, I noticed one little caveat, our current `antora-playbook.yml` declares a `version` attribute and that overrides the `version` attribute that you have in your docs (and they contain different values).
We should therefore merge https://github.com/smallrye/smallrye.github.io/pull/22 first (but I can't do that by myself until someone gives it a +1 review)

**Comment by jmartisk** [comment]
And we're live!

**Comment by radcortez** [comment]
Thanks!

I guess I can also change the version attribute to avoid clashing in the future.

**Comment by jmartisk** [comment]
I suppose we won't have any variables in the global playbook anymore. At least I can't think of a reason why we would need that. So that means your project-scoped variables can be anything you want.
But I'd agree that `version` is a bit too general and one might not immediaterly know what it refers to.

**Comment by radcortez** [comment]
Ok.

I'll change that anyway to me more specific. Thanks!

**Pull request merged**
